lr: 0.001
num_epochs: 1000
weight_decay: 0.01
hidden_features: 32
split:
  seed: 31
  train_ratio: 0.8
  test_ratio: 0.2
  val_ratio: 0.0
feat: 'sig'
graph:
  k: 4
  r: 
sig:
  depth: 4
  normalize: true
  log_signature: false
  time_augment: false
  lead_lag: false
rand:
  num_features: 120
  seed: 42